# Generated by Django 4.1.3 on 2022-11-20 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('identity', models.IntegerField(max_length=11)),
                ('status', models.CharField(choices=[('черновик', 'Черновик'), ('действителен', 'Действителен'), ('истек', 'Истек')], default='черновик', max_length=12)),
                ('summ', models.IntegerField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('executionAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('holderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_contracts', to='estate.holder')),
                ('realtorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_contracts', to='estate.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Immovable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ImageField(upload_to='agency/static/immovables')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('не определен', 'Не определен'), ('дом', 'Дом'), ('квартира', 'Квартира'), ('помещение', 'Помещение'), ('участок', 'Участок')], default='не определен', max_length=12)),
                ('status', models.CharField(choices=[('черновик', 'Черновик'), ('опубликовано', 'Опубликовано'), ('арендовано', 'Арендованно'), ('куплено', 'Куплено')], default='черновик', max_length=12)),
                ('contract', models.BooleanField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('publishAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('contractIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_immovables', to='estate.сontract')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_immovables', to='estate.holder')),
            ],
        ),
    ]
