# Generated by Django 4.1.3 on 2022-11-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_сontract_identity_alter_сontract_summ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сontract',
            new_name='Contract',
        ),
    ]
