# Generated by Django 4.1.3 on 2022-11-20 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_rename_сontract_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'договор', 'verbose_name_plural': 'Договора'},
        ),
        migrations.AlterModelOptions(
            name='holder',
            options={'verbose_name': 'владельца', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='immovable',
            options={'verbose_name': 'недвижимость', 'verbose_name_plural': 'Недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'риелтора', 'verbose_name_plural': 'Риелторы'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='label',
        ),
        migrations.AlterField(
            model_name='contract',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='executionAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='holderName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_contracts', to='estate.holder', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='identity',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='realtorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_contracts', to='estate.realtor', verbose_name='Риелтор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('действителен', 'Действителен'), ('истек', 'Истек')], default='черновик', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='summ',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='mail',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='contract',
            field=models.BooleanField(verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='contractIdentity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_immovables', to='estate.contract', verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_immovables', to='estate.holder', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='publishAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='review',
            field=models.ImageField(upload_to='agency/static/immovables', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('опубликовано', 'Опубликовано'), ('арендовано', 'Арендованно'), ('куплено', 'Куплено')], default='черновик', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='type',
            field=models.CharField(choices=[('не определен', 'Не определен'), ('дом', 'Дом'), ('квартира', 'Квартира'), ('помещение', 'Помещение'), ('участок', 'Участок')], default='не определен', max_length=12, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='immovable',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='mail',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
