# Generated by Django 4.1.3 on 2022-11-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_contract_options_alter_holder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='identity',
            field=models.IntegerField(verbose_name='Номер договора'),
        ),
    ]
